version: "3.5"

volumes:
  mydata:
    # external means it ought to get created outside of compose
    external: true
    name: data

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.python-nginx-uwsgi
      #args:
    image: api-neocampus
    # container-name implies only one instance
    container_name: api-neOCampus
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- .:/app
    network_mode: bridge
    ports:
      - '2225:22'       # sshd
      - '8005:5000'     # Flask
      - '8043:8042'     # stats port
    environment:
      - PYTHONUNBUFFERED=1
    # - FLASK_ENV=development

    mongo:
    image: mongo
    restart: unless-stopped
    # container_name implies only one instance
    container_name: sam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - <mount your docker volume in your database directory>
    network_mode: bridge
    # Port mapping between the localhost and the container
    ports:
      - "27017:27017"     # mongo engine
    command:    --auth --bind_ip_all --wiredTigerCacheSizeGB 24 
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-express
    ports:
      - "27016:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'root'
      ME_CONFIG_MONGODB_SERVER: "<your IP>"
      #ME_CONFIG_MONGODB_SERVER: "frontal"
      ME_CONFIG_SITE_BASEURL: "/mongo"


